[package]
name = "scrypto-test"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
# The Radix Engine Stack
sbor = { path = "../sbor", default-features = false }
native-sdk = { path = "../native-sdk", default-features = false }
transaction = { path = "../transaction", default-features = false }
radix-engine = { path = "../radix-engine", default-features = false, features = ["radix_engine_tests", "db_checker"] }
radix-engine-stores = { path = "../radix-engine-stores", default-features = false }
radix-engine-common = { path = "../radix-engine-common", default-features = false }
radix-engine-interface = { path = "../radix-engine-interface", default-features = false }
radix-engine-store-interface = { path = "../radix-engine-store-interface", default-features = false }
radix-engine-queries = { path = "../radix-engine-queries", default-features = false }
scrypto = { path = "../scrypto", default-features = false }
wabt = { version = "0.10.0" }

# A library used to allow for self-referencing structs in Rust. This is used in the TestRuntime's 
# internal implementation to have do self-referencing.
ouroboros = { version = "0.17.2" }

# A library used for more powerful declarative macros.
paste = { version = "1.0.14" }

# Used for the JSON serialization and deserialization involved in the package compilation
serde_json = { version = "1.0.105" }

[dev-dependencies]
tuple-return = { path = "./tests/blueprints/tuple-return", features = ["test"], default-features = false }

[features]
default = ["std"]

std = ["moka", "sbor/std", "scrypto/std", "native-sdk/std", "transaction/std", "radix-engine/std", "radix-engine-queries/std", "radix-engine-stores/std", "radix-engine-common/std", "radix-engine-interface/std", "radix-engine-store-interface/std", "tuple-return/std"]
alloc = ["lru", "sbor/alloc", "scrypto/alloc", "native-sdk/alloc", "transaction/alloc", "radix-engine/alloc", "radix-engine-queries/alloc", "radix-engine-stores/alloc", "radix-engine-common/alloc", "radix-engine-interface/alloc", "radix-engine-store-interface/alloc", "tuple-return/alloc"]

moka = ["radix-engine/moka"]
lru = ["radix-engine/lru"]

resource_tracker = []

rocksdb = ["radix-engine-stores/rocksdb"]
post_run_db_check = []
use_snapshot = []

[lib]
doctest = false
bench = false